"""
=============================================================================
Pomodoro App - Django Migrations (Initial)
=============================================================================

This is the initial migration file that creates the database tables for
the Pomodoro application models. It is auto-generated by Django's
makemigrations command.

Part of Whole App:
    This migration creates the initial database schema including:
    - Session table for recording Pomodoro sessions
    - DailyStats table for aggregated daily statistics
    - UserSettings table for user timer preferences
    - All necessary indexes and constraints

Architecture:
    - Django migration dependency chain
    - Creates all model tables with proper field types
    - Sets up indexes for efficient querying
    - Establishes foreign key relationships
=============================================================================
"""

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    """Initial migration for the Pomodoro app."""

    initial = True

    dependencies = [
        # Depend on auth for User model
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('focus', 'Focus Session'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], db_index=True, default='focus', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=25, help_text='Planned duration in minutes')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the session was started')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the session was ended', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether the session was completed without interruption')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to='auth.user')),
            ],
            options={
                'verbose_name': 'Pomodoro Session',
                'verbose_name_plural': 'Pomodoro Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_focus_minutes', models.PositiveIntegerField(default=0)),
                ('sessions_completed', models.PositiveIntegerField(default=0)),
                ('total_break_minutes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='auth.user')),
            ],
            options={
                'verbose_name': 'Daily Statistics',
                'verbose_name_plural': 'Daily Statistics',
                'ordering': ['-date'],
                'unique_together': {('date', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_duration', models.PositiveIntegerField(default=25, help_text='Focus session duration in minutes')),
                ('short_break_duration', models.PositiveIntegerField(default=5, help_text='Short break duration in minutes')),
                ('long_break_duration', models.PositiveIntegerField(default=15, help_text='Long break duration in minutes')),
                ('sessions_before_long_break', models.PositiveIntegerField(default=4, help_text='Number of focus sessions before a long break')),
                ('auto_start_breaks', models.BooleanField(default=False, help_text='Automatically start break after focus session')),
                ('auto_start_pomodoros', models.BooleanField(default=False, help_text='Automatically start next focus session after break')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_settings', to='auth.user')),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'started_at'], name='pomodoro_se_user_id_a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_type', 'completed'], name='pomodoro_se_session_d4e5f6_idx'),
        ),
    ]
